name: Jenkins Health Check
on:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches:
      - master
   
jobs:
    build:
        name: Call Jenkins Build
        runs-on: ubuntu-latest
        steps:            
        - name: Jenkins Trigger Job
          uses: appleboy/jenkins-action@master
          with:
            url: "https://ml-poc-jenkins.lambdatest.io"
            user: "shivanshus@lambdatest.com"
            token: ${{ secrets.AUTH_TOKEN }}
            job: "shiv_POC"
